version: '3.7'
services:
  postgres:
    env_file: 
      - .env
    image: postgres:latest
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - /data/postgres/
    networks:
      - otasoft-auth-network

  pgadmin:
    links:
      - postgres:postgres
    env_file: 
      - .env
    image: dpage/pgadmin4
    ports:
      - ${PGADMIN_HOST_PORT}:80
    depends_on:
      - postgres
    networks:
      - otasoft-auth-network

networks: 
  otasoft-auth-network:
    driver: bridge